# Generated by Django 2.1.7 on 2019-03-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_disable_auto_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gccuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
