# Generated by Django 2.1.7 on 2019-03-16 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionForForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='form',
            name='question_list',
        ),
        migrations.AddField(
            model_name='form',
            name='question_list',
            field=models.ManyToManyField(through='gcc.QuestionForForm', to='gcc.Question'),
        ),
        migrations.AddField(
            model_name='questionforform',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcc.Form'),
        ),
        migrations.AddField(
            model_name='questionforform',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcc.Question'),
        ),
    ]
