# Generated by Django 2.1.7 on 2019-03-17 13:16

from django.db import migrations
import gcc.models
import prologin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gcc', '0002_add_question_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventwish',
            name='status',
            field=prologin.models.EnumField(gcc.models.ApplicantStatusTypes, blank=True, choices=[(0, 'incomplete'), (1, 'pending'), (2, 'rejected'), (3, 'selected'), (4, 'accepted'), (5, 'confirmed')], db_index=True, default=1),
        ),
    ]
