# Generated by Django 2.1.7 on 2019-03-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcc', '0003_eventwish_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='status',
        ),
    ]
