# Generated by Django 2.1.7 on 2019-03-17 16:10

from django.db import migrations
import gcc.models
import prologin.models


class Migration(migrations.Migration):

    dependencies = [
        ('gcc', '0004_remove_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventwish',
            name='status',
            field=prologin.models.EnumField(gcc.models.ApplicantStatusTypes, blank=True, choices=[(0, 'Incomplete'), (1, 'Pending'), (2, 'Rejected'), (3, 'Selected'), (4, 'Accepted'), (5, 'Confirmed')], db_index=True, default=0),
        ),
    ]
