# Generated by Django 2.1.7 on 2019-06-15 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcc', '0005_fixdefaultstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='required',
            new_name='always_required',
        ),
    ]
