# Generated by Django 2.1.7 on 2019-06-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcc', '0006_rename_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='finaly_required',
            field=models.BooleanField(default=True),
        ),
    ]
