# Generated by Django 2.2.2 on 2019-07-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('gcc', '0007_question_finaly_required')]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_long',
            field=models.BooleanField(default=True),
        )
    ]
