# Generated by Django 2.1.7 on 2019-03-06 19:38

import centers.models
from django.db import migrations, models
import django.db.models.deletion
import prologin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('postal_code', models.CharField(blank=True, max_length=32, verbose_name='Postal code')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=64, verbose_name='Country')),
                ('name', models.CharField(max_length=64)),
                ('type', prologin.models.EnumField(centers.models.Center.Type, choices=[(0, 'Center'), (1, 'Restaurant'), (2, 'Hotel'), (3, 'Pizzeria'), (4, 'Other')])),
                ('is_active', models.BooleanField(default=True)),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('lng', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('type', 'name', 'city'),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_gender', prologin.models.GenderField(blank=True, choices=[(None, 'Other or prefer not to tell'), (0, 'Male'), (1, 'Female')], null=True, verbose_name='Gender')),
                ('contact_position', models.CharField(blank=True, max_length=128)),
                ('contact_first_name', models.CharField(blank=True, max_length=64)),
                ('contact_last_name', models.CharField(blank=True, max_length=64)),
                ('contact_phone_desk', models.CharField(blank=True, max_length=16)),
                ('contact_phone_mobile', models.CharField(blank=True, max_length=16)),
                ('contact_phone_fax', models.CharField(blank=True, max_length=16)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('type', prologin.models.EnumField(centers.models.Contact.Type, choices=[(0, 'Manager'), (1, 'Contact')], db_index=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='centers.Center')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
